config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root to: 'homes#top'
  get '/home/about', to: 'homes#about', as: 'about'
  resources :users
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  get 'follows/:id' => 'relationships#follows', as: 'follows' # フォローする
  get 'followers/:id' => 'relationships#followers', as: 'followers' # フォロー外す
  post 'books/:id', to: 'books#create'
  post 'users', to: 'books#create'
  post 'users/:id', to: 'books#create'
  post 'follow/:id' => 'relationships#create', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#destroy', as: 'unfollow' # フォロー外す
  get '/search', to: 'search#search'
end

app/models/relationship.rb
class Relationship < ApplicationRecord

    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

    def create
      current_user.follow(params[:id])
      redirect_back(fallback_location: root_path)
    end

    def destroy
      current_user.unfollow(params[:id])
      redirect_back(fallback_location: root_path)
    end

    def follows
      user = User.find(params[:id])
      @users = user.following_user
    end
    def followers
      user = User.find(params[:id])
      @users = user.follower_user
    end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/followers.html.erb
        <h2>Followers</h2>
        <table class="table table-hover table-inverse">
            <thead>
            <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
            </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                    <td>
                        <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
                    </td>
                    <td>
                        <%= user.name %>
                    </td>
                    <td>
                      <%= "フォロー数: #{user.follower.count}" %>
                    </td>
                    <td>
                      <%= "フォロワー数: #{user.followed.count}" %>
                    </td>
                    <td>
                      <% unless user == current_user %>
                        <% if current_user.following?(user) %>
                          <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
                        <% else %>
                          <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
                        <% end %>
                      <% end %>
                    </td>
                    <td><%= link_to "Show", user_path(user) %></td>
                </tr>
              <% end %>
            </tbody>
        </table>

app/views/relationships/follows.html.erb
        <h2>Follows</h2>
        <table class="table table-hover table-inverse">
            <thead>
            <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
            </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                    <td>
                        <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
                    </td>
                    <td>
                        <%= user.name %>
                    </td>
                    <td>
                      <%= "フォロー数: #{user.follower.count}" %>
                    </td>
                    <td>
                      <%= "フォロワー数: #{user.followed.count}" %>
                    </td>
                    <td>
                      <% unless user == current_user %>
                        <% if current_user.following?(user) %>
                          <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
                        <% else %>
                          <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
                        <% end %>
                      <% end %>
                    </td>
                    <td><%= link_to "Show", user_path(user) %></td>
                </tr>
              <% end %>
            </tbody>
        </table>