config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root to: 'homes#top'
  get '/home/about', to: 'homes#about', as: 'about'
  resources :users
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  get 'follows/:id' => 'relationships#follows', as: 'follows' # フォローする
  get 'followers/:id' => 'relationships#followers', as: 'followers' # フォロー外す
  post 'books/:id', to: 'books#create'
  post 'users', to: 'books#create'
  post 'users/:id', to: 'books#create'
  post 'follow/:id' => 'relationships#create', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#destroy', as: 'unfollow' # フォロー外す
  get '/search', to: 'search#search'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, uniqueness: true
  validates :name, length: { in: 2..20 }
  validates :introduction,    length: { maximum: 50 }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人
  attachment :profile_image

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user,   only: [:edit, :update]
  def index
    @users = User.all
    @user = current_user
    @new_book = Book.new
  end
  def show
    @focus_user = User.find(params[:id])
    @books = @focus_user.books
    @user = current_user
    @new_book = Book.new
  end
  def edit
    @user = current_user
    @edit_user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "successfully updated"
    else
      render "edit"
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  def correct_user
    @edit_user = User.find(params[:id])
    redirect_to user_path(current_user) unless @edit_user == current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_search.html.erb
        <table class="table table-hover table-inverse">
            <thead>
            <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
            </tr>
            </thead>
            <tbody>
              <% users.each do |user| %>
                <tr>
                    <td>
                        <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
                    </td>
                    <td>
                        <%= user.name %>
                    </td>
                    <td>
                      <%= "フォロー数: #{user.follower.count}" %>
                    </td>
                    <td>
                      <%= "フォロワー数: #{user.followed.count}" %>
                    </td>
                    <td>
                      <% unless user == current_user %>
                        <% if current_user.following?(user) %>
                          <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
                        <% else %>
                          <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
                        <% end %>
                      <% end %>
                    </td>
                    <td><%= link_to "Show", user_path(user) %></td>
                </tr>
              <% end %>
            </tbody>
        </table>

app/views/users/edit.html.erb
<main>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
      <span style="color: red">error</span>
      <ul style="color: red">
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p id="notice"><%=  flash[:notice] %></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
        <%= form_with model:@user, local:true do |f| %>
          <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, autofocus: true %>
          </div>
          <div class="form-group">
          <%= f.label :profile_image %>
          <%= f.attachment_field :profile_image %>
          </div>
          <div class="form-group">
          <%= f.label :introduction %>
          <%= f.text_area :introduction %>
          </div>
          <div class="form-group">
          <%= f.submit "Update User" %>
          </div>
        <% end %>
      </div>
    </div>

  </div>
</main>

app/views/users/index.html.erb
<main>
  <p id="notice"><%=  flash[:notice] %></p>
  <div class="container px-5 px-sm-0">

    <div class="row">
      <div class="col-xs-3 col-md-3">
        <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %>
        <table class="table">
          <tbody>
            <tr></tr>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to "", edit_user_path(@user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
        </div>
        <h2 class="mt-3">New book</h2>
        <%= form_with model: @new_book, local: true do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title %>
        </div>
        <div class="form-group">
          <%= f.label :body %>
          <%= f.text_area :body %>
        </div>
        <%= f.submit 'Create Book', class: "btn btn-success" %>
        <% end %>
      </div>
      <div class="col-xs-9 col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table table-hover table-inverse">
            <thead>
            <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
            </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                    <td>
                        <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
                    </td>
                    <td>
                        <%= user.name %>
                    </td>
                    <td><%= link_to "Show", user_path(user) %></td>
                </tr>
              <% end %>
            </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <p id="notice"><%=  flash[:notice] %></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
    <div class="col-xs-3 col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag @focus_user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %>
      <table class="table">
        <tbody>
          <tr>
          <th>comments</th>
          <th><%= @focus_user.book_comments.count %></th>
          </tr>
          <tr>
          <th>name</th>
          <th><%= @focus_user.name %></th>
          </tr>
          <tr>
          <th>introduction</th>
          <th><%= @focus_user.introduction %></th>
          </tr>
          <tr>
          <tr>
            <th>follows</th>
            <th><%= link_to @focus_user.follower.count, follows_path(@focus_user) %></th>
          </tr>
          <tr>
            <th>folowers</th>
            <th><%= link_to @focus_user.followed.count, followers_path(@focus_user) %></th>
          </tr>
        </tbody>
      </table>
    <p>
      <% unless @focus_user == current_user %>
        <% if current_user.following?(@focus_user) %>
          <%= link_to 'フォロー外す', unfollow_path(@focus_user.id), method: :POST, class: "btn btn-success" %>
        <% else %>
          <%= link_to 'フォローする', follow_path(@focus_user.id), method: :POST, class: "btn btn-success" %>
        <% end %>
      <% end %>
    </p>


      <div class="row">
      <%= link_to '', edit_user_path(@focus_user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
      </div>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: @new_book, local: true do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title %>
        </div>
        <div class="form-group">
          <%= f.label :body %>
          <%= f.text_area :body %>
        </div>
        <%= f.submit 'Create Book', class: "btn btn-success" %>
        <% end %>
    </div>
    <div class="col-xs-9 col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
            <%= link_to (attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40"), user_path(book.user) %>
            </td>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    </div>
  </div>
</main>