config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root to: 'homes#top'
  get '/home/about', to: 'homes#about', as: 'about'
  resources :users
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  get 'follows/:id' => 'relationships#follows', as: 'follows' # フォローする
  get 'followers/:id' => 'relationships#followers', as: 'followers' # フォロー外す
  post 'books/:id', to: 'books#create'
  post 'users', to: 'books#create'
  post 'users/:id', to: 'books#create'
  post 'follow/:id' => 'relationships#create', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#destroy', as: 'unfollow' # フォロー外す
  get '/search', to: 'search#search'
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true
    validates :body, length: { maximum: 200 }

    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :book_comments, dependent: :destroy

    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user,   only: [:edit, :update]
  def index
    @books = Book.all
    @new_book = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @user = current_user
    @new_book = Book.new
    @book_comment = BookComment.new
  end

  def create
    @user = current_user
    @books = Book.all
    @new_book = Book.new(edit_book_params)
    @new_book.user_id = current_user.id



    if @new_book.save
      redirect_to book_path(@new_book.id), notice: "successfully created"
    else
      render "index"
    end
  end

  def edit
    @user = current_user
    @book = Book.find(params[:id])
  end

  def update
    @user = current_user
    @book = Book.find(params[:id])
    if @book.update(edit_book_params)
      redirect_to book_path(@book), notice: "successfully updated"
    else
      render "edit"
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path, notice: "successfully destroy"
  end

  private
  def book_params
    params.permit(:title, :body)
  end
  def edit_book_params
    params.require(:book).permit(:title, :body)
  end
  def correct_user
    @edit_user = Book.find(params[:id]).user
    redirect_to books_path unless @edit_user == current_user
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_search.html.erb
<table class="table table-hover table-inverse">
            <thead>
            <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
            </tr>
            </thead>
            <tbody>
              <% books.each do |book| %>
              <tr>
              <td>
              <%= link_to (attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40"), user_path(book.user) %>
              </td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
              </tr>
              <% end %>
            </tbody>
        </table>

app/views/books/edit.html.erb
<main>
  <p id="notice"><%=  flash[:notice] %></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
        <% if @book.errors.any? %>
          <div class="alert alert-danger">
            <span style="color: red">error</span>
            <ul style="color: red">
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <%= form_with model:@book, local: true do |f| %>
          <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title %>
          </div>
          <div class="form-group">
          <%= f.label :body %>
          <%= f.text_area :body %>
          </div>
          <div class="form-group">
          <%= f.submit 'Update Book', class: "btn btn-primary" %>
          </div>
        <% end %>
        <%= link_to "Show", book_path(@book) %> |
        <%= link_to "Back", books_path %>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
  <p id="notice"><%=  flash[:notice] %></p>
  <div class="container px-5 px-sm-0">

    <div class="row">
      <%= render 'layouts/user', user: @user, new_book: @new_book %>
      <div class="col-xs-9 col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
            <thead>
            <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
            </tr>
            </thead>
            <tbody>
              <% @books.each do |book| %>
              <tr>
              <td>
              <%= link_to (attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40"), user_path(book.user) %>
              </td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
              <td id="likes_buttons_<%= book.id %>">
              <%= render partial: 'favorites/favorite', locals: { book: book} %>
              </td>
              <td>コメント数：<%= book.book_comments.count %></td>
              </tr>
              <% end %>
            </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/books/show.html.erb
<main>
  <p id="notice"><%=  flash[:notice] %></p>
  <div class="container px-5 px-sm-0">

    <div class="row">
      <%= render 'layouts/user', user: @book.user, new_book: @new_book %>
      <div class="col-xs-9 col-md-8 offset-md-1">
    		<h2>Book detail</h2>
    		<table class="table">
    		  <tbody><tr>
            <td>
              <%= link_to user_path(@book.user) do %>
                <%= attachment_image_tag @book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %><br>
                <%= @book.user.name %>
              <% end %>
            </td>
            <td><%= @book.title %></td>
            <td><%= @book.body %></td>
            <td id="likes_buttons_<%= @book.id %>">
            <%= render partial: 'favorites/favorite', locals: { book: @book} %>
            </td>
            <td>コメント数：<%= @book.book_comments.count %></td>
            <% if@book.user.id == @current_user.id%>
            <td><%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "Are you sure？", class: "btn btn-sm btn-danger" %></td>
            <% end %>
          </tr>
        </tbody>
        </table>
        <div id="comments_<%= @book.id %>">
          <%= render partial: 'book_comments/comments', locals: {book: @book} %>
        </div>
        <div class="row">
          <div class="new-comment">
          <%= form_with(model:[@book, @book_comment], class: :'js-form') do |f| %>
          <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに", class: "js-form" %>
          <%= f.submit "Create Book comment"%>
          <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>