config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root to: 'homes#top'
  get '/home/about', to: 'homes#about', as: 'about'
  resources :users
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  get 'follows/:id' => 'relationships#follows', as: 'follows' # フォローする
  get 'followers/:id' => 'relationships#followers', as: 'followers' # フォロー外す
  post 'books/:id', to: 'books#create'
  post 'users', to: 'books#create'
  post 'users/:id', to: 'books#create'
  post 'follow/:id' => 'relationships#create', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#destroy', as: 'unfollow' # フォロー外す
  get '/search', to: 'search#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true
    validates :body, length: { maximum: 200 }

    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :book_comments, dependent: :destroy

    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    validates :comment, presence: true
    belongs_to :user
    belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :book
    validates_uniqueness_of :book_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord

    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, uniqueness: true
  validates :name, length: { in: 2..20 }
  validates :introduction,    length: { maximum: 50 }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人
  attachment :profile_image

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
        user_path(current_user)
    end

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user,   only: [:edit, :update]
  def index
    @books = Book.all
    @new_book = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @user = current_user
    @new_book = Book.new
    @book_comment = BookComment.new
  end

  def create
    @user = current_user
    @books = Book.all
    @new_book = Book.new(edit_book_params)
    @new_book.user_id = current_user.id



    if @new_book.save
      redirect_to book_path(@new_book.id), notice: "successfully created"
    else
      render "index"
    end
  end

  def edit
    @user = current_user
    @book = Book.find(params[:id])
  end

  def update
    @user = current_user
    @book = Book.find(params[:id])
    if @book.update(edit_book_params)
      redirect_to book_path(@book), notice: "successfully updated"
    else
      render "edit"
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path, notice: "successfully destroy"
  end

  private
  def book_params
    params.permit(:title, :body)
  end
  def edit_book_params
    params.require(:book).permit(:title, :body)
  end
  def correct_user
    @edit_user = Book.find(params[:id]).user
    redirect_to books_path unless @edit_user == current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    def create
        @book = Book.find(params[:book_id])
        favorite = current_user.favorites.new(book_id: @book.id)
        favorite.save
    end

    def destroy
        @book = Book.find(params[:book_id])
        favorite = current_user.favorites.find_by(book_id: @book.id)
        favorite.destroy
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def top
    end
    def about
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    def search
        @model = params["model"]
        @content = params["content"]
        @method = params["method"]
        @records = search_for(@model, @content, @method)
    end

    private
    def search_for(model, content, method)
        if model == 'user'
          if method == 'perfect'
            User.where(name: content)
          else
            User.where('name LIKE ?', '%'+content+'%')
          end
        elsif model == 'book'
          if method == 'perfect'
            Book.where(title: content)
          else
            Book.where('title LIKE ?', '%'+content+'%')
          end
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user,   only: [:edit, :update]
  def index
    @users = User.all
    @user = current_user
    @new_book = Book.new
  end
  def show
    @focus_user = User.find(params[:id])
    @books = @focus_user.books
    @user = current_user
    @new_book = Book.new
  end
  def edit
    @user = current_user
    @edit_user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "successfully updated"
    else
      render "edit"
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  def correct_user
    @edit_user = User.find(params[:id])
    redirect_to user_path(current_user) unless @edit_user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_user.html.erb
      <div class="col-xs-3 col-md-3">
        <h2>User info</h2>
        <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %>
        <table class="table">
          <tbody>
            <tr></tr>
            <tr>
              <th>name</th>
              <th><%= user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= user.introduction %></th>
            </tr>
            <tr>
              <th>follows</th>
              <th><%= link_to user.follower.count, follows_path(user) %></th>
            </tr>
            <tr>
              <th>folowers</th>
              <th><%= link_to user.followed.count, followers_path(user) %></th>
            </tr>
          </tbody>

        </table>
        <div class="row">
          <%= link_to "", edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
        </div>
        <h2 class="mt-3">New book</h2>
        <%= form_with model: new_book, local: true do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title %>
        </div>
        <div class="form-group">
          <%= f.label :body %>
          <%= f.text_area :body %>
        </div>
        <%= f.submit 'Create Book', class: "btn btn-success" %>
        <% end %>
      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <span class="navbar-brand">Bookers</span>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <%= form_tag(search_path, method: :get) do %>
              <%= text_field_tag 'content' %>
              <%= select_tag 'model', options_for_select({ "User" => "user", "Book" => "book" }) %>
              <%= select_tag 'method', options_for_select({ "完全一致" => "perfect", "部分一致" => "partial" }) %>
              <%= submit_tag '検索' %>
            <% end %>
            <li><%= link_to " Home", user_path(current_user), class: "fas fa-home nav-link text-light" %></li>
            <li><%= link_to " Users", users_path, class: "fas fa-users nav-link text-light" %></li>
            <li><%= link_to " Books", books_path, class: "fas fa-book-open nav-link text-light" %></li>
            <li>
            <%= link_to " logout", destroy_user_session_path, class: 'fas fa-sign-out-alt nav-link text-light', method: :delete %>
            </li>
          <% else %>

            <li><%= link_to " Home", root_path, class: "fas fa-home nav-link text-light" %></li>
            <li><%= link_to " About", about_path, class: "fas fa-link nav-link text-light" %></li>
            <li>
              <%= link_to " sign up", new_user_registration_path, class: 'fas fa-user-plus nav-link text-light' %>
            </li>
            <li>
              <%= link_to " login", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>
    <%= yield %>

    <footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>
  </body>
</html>